// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3fd0717c-da42-4165-85ac-5913eaf1e452",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CJDqbdlJT",
    "aws_user_pools_web_client_id": "3u4qgehj78u5aeegjd79ahocid",
    "aws_cloud_logic_custom": [
        {
            "name": "leanAnalyticsApi",
            "endpoint": "https://nw7ipb8huf.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "lean-analytics-hosting-bucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3keiwz6zjmx88.cloudfront.net",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "experiments",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
